import { chmodSync, cpSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { FIXTURE_DIR } from "../paths.js";
import { loadFixtureState } from "./fixture.js";
import { ALLOWED_LABELS, type PullRequest } from "./types.js";

/**
 * Writes everything you need to recreate the tiny-shop sandbox on GitHub:
 *
 *   <dir>/repo/          the code for the default branch
 *   <dir>/issues/NN.md   one body per issue
 *   <dir>/prs/NN.md      one description per pull request
 *   <dir>/patches/       one git patch per pull request
 *   <dir>/seed.sh        gh commands that create labels, issues, branches and PRs
 *
 * Run seed.sh from inside a clone of your sandbox repo. docs/LIVE_MODE.md walks through it.
 */
export function exportSandbox(outDir: string, fixtureDir = FIXTURE_DIR): string[] {
  const state = loadFixtureState(fixtureDir);
  rmSync(outDir, { recursive: true, force: true });
  for (const sub of ["repo", "issues", "prs", "patches"]) mkdirSync(path.join(outDir, sub), { recursive: true });
  cpSync(path.join(fixtureDir, "repo"), path.join(outDir, "repo"), { recursive: true });

  const pad = (n: number) => String(n).padStart(2, "0");
  const lines = [
    "#!/usr/bin/env bash",
    "# Seeds a GitHub sandbox repo with tiny-shop's code, issues and pull requests.",
    "# Run it from the root of a clone of your sandbox repo, with gh logged in.",
    "# Generated by npm run sandbox:export; see docs/LIVE_MODE.md.",
    "set -euo pipefail",
    'EXPORT_DIR="$(cd "$(dirname "$0")" && pwd)"',
    "",
    "echo 'Labels'",
    ...ALLOWED_LABELS.map((l) => `gh label create ${q(l)} --force >/dev/null`),
    "",
    "echo 'Code on the default branch'",
    'cp -R "$EXPORT_DIR/repo/." .',
    `git add -A && git commit -m ${q("tiny-shop 1.2.0")} && git push`,
    "",
    "echo 'Issues (comments from other people are not recreated)'",
  ];
  for (const issue of state.issues) {
    writeFileSync(path.join(outDir, "issues", `${pad(issue.number)}.md`), issue.body + "\n");
    const labels = issue.labels.map((l) => ` --label ${q(l)}`).join("");
    lines.push(`url=$(gh issue create --title ${q(issue.title)} --body-file "$EXPORT_DIR/issues/${pad(issue.number)}.md"${labels})`);
    lines.push(`echo "fixture #${issue.number} -> $url"`);
    if (issue.state === "closed") lines.push(`gh issue close "$url" --reason ${q(issue.stateReason === "not_planned" ? "not planned" : "completed")}`);
  }
  lines.push("", "echo 'Pull requests'");
  for (const pr of state.pullRequests) {
    writeFileSync(path.join(outDir, "prs", `${pad(pr.number)}.md`), pr.body + "\n");
    writeFileSync(path.join(outDir, "patches", `pr-${pr.number}.patch`), toGitPatch(pr));
    lines.push(
      `git switch -c ${q(pr.head)}`,
      `git apply "$EXPORT_DIR/patches/pr-${pr.number}.patch"`,
      `git add -A && git commit -m ${q(pr.title)} && git push -u origin ${q(pr.head)}`,
      `url=$(gh pr create --title ${q(pr.title)} --body-file "$EXPORT_DIR/prs/${pad(pr.number)}.md" --base ${q(pr.base)} --head ${q(pr.head)})`,
      `echo "fixture PR #${pr.number} -> $url"`,
      `git switch ${q(state.defaultBranch)}`,
    );
  }
  lines.push("", "echo 'Done. Numbers on GitHub can differ from the fixture; use the mapping above.'");
  const script = path.join(outDir, "seed.sh");
  writeFileSync(script, lines.join("\n") + "\n");
  chmodSync(script, 0o755);
  return lines;
}

/** A pull request's files as one patch that `git apply` accepts. */
export function toGitPatch(pr: PullRequest): string {
  return pr.files
    .map((f) => `diff --git a/${f.path} b/${f.path}\n--- a/${f.path}\n+++ b/${f.path}\n${f.patch}\n`)
    .join("");
}

/** Single-quotes a string for bash. */
function q(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const out = path.resolve(process.argv[2] ?? "sandbox-export");
  exportSandbox(out);
  console.log(`Wrote the sandbox to ${out}. Next: follow docs/LIVE_MODE.md and run ${path.join(out, "seed.sh")} in your sandbox clone.`);
}
